# This file is included only for launchers to display mod metadata. It is not read by NeoForge in production.
modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/decce6/Ixeris/issues"
license = "${mod_license}"
clientSideOnly=true

[[mods]]
    authors = "decce"
    credits = "LitnhJacuzzi"
    description = '''${mod_description}'''
    displayName = "${mod_name}"
    displayURL = "https://modrinth.com/mod/ixeris"
    logoFile = "ixeris.png"
    logoBlur = false
    modId = "${modid}_dummy"
    version = "${mod_version_full}"

[[dependencies.${modid}]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.${modid}]]
    modId = "minecraft"
    versionRange = "${minecraft_supported_forge}"
    type = "required"