modLoader = "javafml"
loaderVersion = "[2,)"
issueTrackerURL = "https://github.com/decce6/Ixeris/issues"
license = "${mod_license}"
clientSideOnly=true

[[mods]]
    authors = "decce"
    credits = "LitnhJacuzzi"
    description = '''${mod_description}'''
    displayName = "${mod_name}"
    displayURL = "https://modrinth.com/mod/ixeris"
    logoFile = "ixeris.png"
    logoBlur = false
    modId = "ixeris"
    version = "${mod_version_full}"

[[mixins]]
    config = "ixeris.mixins.json"

[[dependencies.ixeris]]
    modId = "neoforge"
    type = "required"
    ordering = "NONE"
    side = "BOTH"

[[dependencies.ixeris]]
    modId = "minecraft"
    versionRange = "${minecraft_supported_forge}"
    type = "required"